exports_files([
    "consul/consul.json",
    "consul/default-policy.hcl",
    "debian/postinst.sh",
    "debian/prerm.sh",
    "nomad/config/nomad.hcl",
    "nomad/config/elasticsearch/unicast_hosts.tpl",
    "nomad/config/zookeeper/config/zoo.tpl",
    "nomad/config/zookeeper/config/zoo.cfg",
    "nomad/config/zookeeper/config/zoo_replicated.cfg.dynamic",
    "networkd/10-radix-consul",
    "networkd/10-radix-nomad",
    "redhat/rpm.spec",
    "systemd/consul.env.conf",
    "systemd/consul.service",
    "systemd/nomad.env.conf",
    "systemd/nomad.service",
    "systemd/vault.service",
    "systemd/vault.env.conf",
    "vault/nomad-cluster-role.json",
    "vault/nomad-server-policy.hcl",
    "vault/read-aws-policy.hcl",
    "vault/vault_config.conf",
    "terraform/main/main.tf",
    "terraform/main/variables.tf",

    # APPRISE MODULE
    "terraform/apprise/apprise.tmpl",
    "terraform/apprise/main.tf",
    "terraform/apprise/outputs.tf",
    "terraform/apprise/variables.tf",

    # RUNTIME MODULE
    "terraform/runtime/runtime.tmpl",
    "terraform/runtime/main.tf",
    "terraform/runtime/outputs.tf",
    "terraform/runtime/variables.tf",

    # S3LTS MODULE
    "terraform/s3lts/s3lts.tmpl",
    "terraform/s3lts/main.tf",
    "terraform/s3lts/outputs.tf",
    "terraform/s3lts/variables.tf",

    # ZOOKEEPER MODULE
    "terraform/zookeeper/zookeeper.tmpl",
    "terraform/zookeeper/main.tf",
    "terraform/zookeeper/outputs.tf",
    "terraform/zookeeper/variables.tf",

    # KAFKA MODULE
    "terraform/kafka/kafka.tmpl",
    "terraform/kafka/main.tf",
    "terraform/kafka/outputs.tf",
    "terraform/kafka/variables.tf",

    # KAFKA COMPANIONS MODULE
    "terraform/kafka_companions/kafka_companions.tmpl",
    "terraform/kafka_companions/main.tf",
    "terraform/kafka_companions/outputs.tf",
    "terraform/kafka_companions/variables.tf",

    # RETOOL/POSTGRES MODULE
    "terraform/retool/retool.tmpl",
    "terraform/retool/main.tf",
    "terraform/retool/outputs.tf",
    "terraform/retool/variables.tf",

    # ELEMENTAL MODULE
    "terraform/elemental/elemental.tmpl",
    "terraform/elemental/main.tf",
    "terraform/elemental/outputs.tf",
    "terraform/elemental/variables.tf",

    # ELASTICSEARCH MODULE
    "terraform/elasticsearch/elastic_search.tmpl",
    "terraform/elasticsearch/main.tf",
    "terraform/elasticsearch/outputs.tf",
    "terraform/elasticsearch/variables.tf",

    # MINIO MODULE
    "terraform/minio/minio.tmpl",
    "terraform/minio/main.tf",
    "terraform/minio/outputs.tf",
    "terraform/minio/variables.tf",

    # YUGABYTE MODULE
    "terraform/yugabyte/yugabyte.tmpl",
    "terraform/yugabyte/main.tf",
    "terraform/yugabyte/outputs.tf",
    "terraform/yugabyte/variables.tf",

    # ES KAFKA CONNECTOR MODULE
    "terraform/es_kafka_connector/es_kafka_connector.tmpl",
    "terraform/es_kafka_connector/main.tf",
    "terraform/es_kafka_connector/outputs.tf",
    "terraform/es_kafka_connector/variables.tf",

    # RETOOL PG KAFKA CONNECTOR MODULE
    "terraform/retool_pg_kafka_connector/retool_pg_kafka_connector.tmpl",
    "terraform/retool_pg_kafka_connector/main.tf",
    "terraform/retool_pg_kafka_connector/outputs.tf",
    "terraform/retool_pg_kafka_connector/variables.tf",

    # YUGABYTE KAFKA CONNECTOR MODULE
    "terraform/yugabyte_kafka_connector/yugabyte_kafka_connector.tmpl",
    "terraform/yugabyte_kafka_connector/main.tf",
    "terraform/yugabyte_kafka_connector/outputs.tf",
    "terraform/yugabyte_kafka_connector/variables.tf",
])
