exports_files([
    "consul/consul-server.json",
    "consul/consul-client.json",
    "consul/actor-policy.hcl",
    "consul/default-policy.hcl",
    "container_networking/cni.conf",
    "debian/postinst.sh",
    "debian/prerm.sh",
    "nomad/config/nomad.hcl",
    "nomad/nomad-windows.hcl",
    "networkd/10-radix-consul",
    "networkd/10-radix-nomad",
    "redhat/rpm.spec",
    "systemd/consul.env.conf",
    "systemd/consul.service",
    "systemd/consul-template.env.conf",
    "systemd/consul-template.service",
    "systemd/nomad.env.conf",
    "systemd/nomad.service",
    "systemd/timberland-svc.service",
    "systemd/vault.service",
    "systemd/vault.env.conf",
    "vault/aws-cred-role.json",
    "vault/tls-cert-role.json",
    "vault/tls-cert-policy.hcl",
    "vault/read-aws-policy.hcl",
    "vault/actor-acl-token-policy.hcl",
    "vault/nomad-server-policy.hcl",
    "vault/read-flag-config-policy.hcl",
    "vault/read-certs-policy.hcl",
    "vault/remote-access-policy.hcl",
    "vault/read-message-targets-policy.hcl",
    "vault/vault_config.conf",

    # TLS
    "consul-template/ca/cert.pem.tpl",
    "consul-template/ca/combined.pem.tpl",
    "consul-template/consul/cert.pem.tpl",
    "consul-template/consul/key.pem.tpl",
    "consul-template/nomad/cert.pem.tpl",
    "consul-template/nomad/key.pem.tpl",
    "consul-template/nomad/cli-cert.pem.tpl",
    "consul-template/nomad/cli-key.pem.tpl",
    "consul-template/vault/cert.pem.tpl",
    "consul-template/vault/key.pem.tpl",
    "consul-template/cli/cert.pem.tpl",
    "consul-template/cli/key.pem.tpl",
    "consul-template/config.hcl",
    "consul-template/config-windows.hcl",
    "update/cloud_upload_config.sh",
    "terraform/main/variables.tf",
    "terraform/main/outputs.tf",

    # WINDOWS
    "windows/postinst.bat",

    # AWS KEYS MODULE
    "terraform/aws_keys/main.tf",
    "terraform/aws_keys/outputs.tf",

    # ZOOKEEPER MODULE
    "terraform/zookeeper/zookeeper.tmpl",
    "terraform/zookeeper/main.tf",
    "terraform/zookeeper/outputs.tf",
    "terraform/zookeeper/variables.tf",

    # KAFKA MODULE
    "terraform/kafka/kafka.tmpl",
    "terraform/kafka/main.tf",
    "terraform/kafka/outputs.tf",
    "terraform/kafka/variables.tf",

    # KAFKA COMPANIONS MODULE
    "terraform/kafka_companions/kafka_companions.tmpl",
    "terraform/kafka_companions/main.tf",
    "terraform/kafka_companions/outputs.tf",
    "terraform/kafka_companions/variables.tf",

    # ELASTICSEARCH MODULE
    "terraform/elasticsearch/elasticsearch.tmpl",
    "terraform/elasticsearch/kibana.tmpl",
    "terraform/elasticsearch/main.tf",
    "terraform/elasticsearch/outputs.tf",
    "terraform/elasticsearch/variables.tf",

    # MINIO MODULE
    "terraform/minio/minio.tmpl",
    "terraform/minio/main.tf",
    "terraform/minio/outputs.tf",
    "terraform/minio/variables.tf",

    # YUGABYTE MODULE
    "terraform/yugabyte/yb_masters.tmpl",
    "terraform/yugabyte/yb_tservers.tmpl",
    "terraform/yugabyte/main.tf",
    "terraform/yugabyte/outputs.tf",
    "terraform/yugabyte/variables.tf",

    # ES KAFKA CONNECTOR MODULE
    "terraform/es_kafka_connector/es_kafka_connector.tmpl",
    "terraform/es_kafka_connector/main.tf",
    "terraform/es_kafka_connector/outputs.tf",
    "terraform/es_kafka_connector/variables.tf",

    # YUGABYTE KAFKA CONNECTOR MODULE
    "terraform/yugabyte_kafka_connector/yugabyte_kafka_connector.tmpl",
    "terraform/yugabyte_kafka_connector/main.tf",
    "terraform/yugabyte_kafka_connector/outputs.tf",
    "terraform/yugabyte_kafka_connector/variables.tf",

    # NGINX MODULE
    "terraform/nginx/nginx.tmpl",
    "terraform/nginx/main.tf",
    "terraform/nginx/outputs.tf",
    "terraform/nginx/variables.tf",
])
