#!/bin/bash

if (( $EUID != 0 )); then
  exec sudo java -jar /opt/radix/timberland/exec/timberland-bin_deploy.jar "$@"
else
  exec java -jar /opt/radix/timberland/exec/timberland-bin_deploy.jar "$@"
fi