#!/bin/bash

if [ "$EUID" -ne 0 ]
then
    echo "Please run this command as root."
    exit 1
fi

./uninstall

echo "Extracting timberland files..."

if ! tar -xf ./TIMBERLAND_TAR -C /; then
    echo "Error extracting timberland files."
    exit 1
fi

echo "Running post-install script..."
./postinst

echo "Installation complete!"

# Symlink to the path

ln -s /opt/radix/timberland/exec/timberland /usr/local/bin/timberland

echo "Run 'timberland start' to begin using timberland."


