package(
    default_visibility = ["//visibility:public"],
)

py_binary(
    name = "construct_rpm_spec",
    srcs = ["construct_rpm_spec.py"],
    deps = [],
)

py_binary(
    name = "mark_image_digests",
    srcs = ["mark_image_digests.py"],
    deps = [],
)

py_binary(
    name = "build_structured_tar",
    srcs = ["build_structured_tar.py"],
    deps = [],
)
