scala_library(
    name = "helm-interfaces",
    srcs = glob(["src/main/scala/**/*.scala"]),
    visibility = ["//utils/helm:__subpackages__"],
    exports = [
        "//utils/helm/core/shared:helm-core-lib",
    ],
    deps = [
        "//utils/helm/core/shared:helm-core-lib",
    ],
)